FROM node:22-alpine

RUN apk add --no-cache \
    curl \
    bash \
    python3 \
    make \
    g++ \
    openssl

WORKDIR /app

COPY package*.json ./

RUN npm install

COPY server ./server
COPY prisma ./prisma
COPY tsconfig.json ./

RUN npx prisma generate

EXPOSE 3001

ENV PORT=3001

CMD ["sh", "-c", "sleep 5 && npx prisma migrate deploy && npx tsx server/index.ts"]
